### ISSUE TITLE
Write script to save user preference information in cookies

### ISSUE THREAD

**Issue by AlexiCat** [comp129-spr17/todoteamname#20]
Done when a user can return to the site and the information is already filled in for them (both "preferences" and "list me")

**Comment by onzfonz** [comment]
Glad you guys are commenting and using the issue thread to decide whether or not this features is done.  In the future you could then either decide to close the issue or bring up a new issue, leave it open etc

**Comment by onzfonz** [comment]
Another thing that I noticed is that the cookie does not update, so like you change the name say list me I got an error, and then it went back to the old values even though thing said something was missing.  A bigger error was the fact that some sliders came back as text boxes the next time I would open up list me if I did it in succession
